package org.com.teja.WebApplicationX;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.com.teja.WebApplicationX.model.Comment;
import org.com.teja.WebApplicationX.model.Message;

public class test {
	
	public Map<Integer,Comment> CommentIdMap(int NumberOfComments, int NumberOfMessages){
		Map<Integer,Comment> commentmapx = new HashMap<Integer,Comment>();
		for(int i=1;i<=NumberOfComments;i++)
		{
			Comment comment = new Comment();
			comment.setComment("M:"+NumberOfMessages+"comment"+i);
			comment.setCommentid(i);
//			commentmapx.put(comment.getCid(), comment );
     		commentmapx.put(comment.getCommentid(), comment );

			System.out.println("M:"+NumberOfMessages+" comment "+i);
			
		}
		System.out.println("---------------------------------------------------------------------");
		return commentmapx;
		
	}
	public Map<Integer, Map<Message, Map<Integer,Comment>>> MidMesssageCommentListMap(int NumberOfComments, int NumberOfMessages){
		Map<Integer, Map<Message, Map<Integer,Comment>>> messagesmap= 
				new HashMap<Integer, Map<Message, Map<Integer,Comment>>>();
		
		
		
		for(int x=1; x<=NumberOfMessages; x++){
			Map<Message, Map<Integer, Comment>> messagecommentmap =
		               new HashMap<Message, Map<Integer,Comment>>();
			//Message message=new Message();
			Message message= new Message(x,"Message"+x,"Author"+x);
			messagecommentmap.put(message, CommentIdMap(NumberOfComments,x));
			messagesmap.put(message.getId(), messagecommentmap);
			System.out.println(message.getId()+"th message generated by "+message.getAuthor());
			
			System.out.println("---------------------------------------------------------------------");
			
		}
		
		
		
		return messagesmap;
		
	}
	
	
	
	public static void main(String args[]) {
	
		
	
	test test = new test();
	System.out.println("Map Generation Started?????????????????????????????????????????????????????????");
	Map<Integer, Map<Message, Map<Integer,Comment>>>  MessagesMap = test.MidMesssageCommentListMap(2500, 2500);
	System.out.println("Map Generation Completed!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!");
	
//Message m=new Message();
//Comment c = new Comment();
//	
//	MessagesMap.put(7,put(m.getMessage(), put(7, new Comment.setComment("was up"))));
//	
//	
	
	}

}
